# Generated by Django 2.2.1 on 2020-05-01 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200501_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='userRating',
        ),
    ]
