# Generated by Django 2.2.1 on 2020-05-01 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_book_userrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='userRating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
