# Generated by Django 2.2.1 on 2020-05-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200502_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
